
## Ordrup Jagtvej 21, 2920 Charlottenlund

## /bygning
## husnummer=adresseadgangsid

## "byg038SamletBygningsareal": 107 (Boligareal)
## "byg039BygningensSamledeBoligAreal": 113 (Grundareal)

GET https://services.datafordeler.dk/BBR/BBRPublic/1/REST/bygning?husnummer=0a3f507b-f767-32b8-e044-0003ba298018&username=WWCHFFIZAW&password=PROGeksamen2026!&format=JSO

## Output:

HTTP/1.1 200 OK
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8
Server: datafordeler.dk
SwitchboardPerformanceInMs: 97.5534
Access-Control-Allow-Origin: *
X-POWERED-BY: datafordeler.dk
Date: Fri, 01 May 2026 09:02:07 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

[
  {
    "datafordelerOpdateringstid": "2021-04-03T03:06:57.664277+02:00",
    "byg007Bygningsnummer": 2,
    "byg021BygningensAnvendelse": "920",
    "byg026Opførelsesår": 1982,
    "byg032YdervæggensMateriale": "90",
    "byg033Tagdækningsmateriale": "3",
    "byg037KildeTilBygningensMaterialer": "2",
    "byg041BebyggetAreal": 24,
    "byg053BygningsarealerKilde": "2",
    "byg056Varmeinstallation": "9",
    "byg094Revisionsdato": "2017-03-23T00:00:00.000000+01:00",
    "byg133KildeTilKoordinatsæt": "M",
    "byg134KvalitetAfKoordinatsæt": "3",
    "byg135SupplerendeOplysningOmKoordinatsæt": "31",
    "byg136PlaceringPåSøterritorie": "0",
    "byg404Koordinat": "POINT(721573.29 6176137.54)",
    "byg406Koordinatsystem": "5",
    "forretningshændelse": "Bygning",
    "forretningsområde": "54.15.05.05",
    "forretningsproces": "0",
    "grund": "04999352-9a5b-46ab-b669-1b2c2f890a82",
    "husnummer": "0a3f507b-4e55-32b8-e044-0003ba298018",
    "id_lokalId": "2ab8288a-16be-4bed-bf07-056d0c4a81e9",
    "id_namespace": "http://data.gov.dk/bbr/bygning",
    "jordstykke": "100028488",
    "kommunekode": "0147",
    "registreringFra": "2020-06-12T18:24:45.000021+02:00",
    "registreringsaktør": "BBR",
    "status": "10",
    "virkningFra": "2020-06-12T18:24:45.000021+02:00",
    "virkningsaktør": "BBR21"
  },
  {
    "datafordelerOpdateringstid": "2021-04-03T00:33:02.582612+02:00",
    "byg007Bygningsnummer": 1,
    "byg021BygningensAnvendelse": "429",
    "byg026Opførelsesår": 1965,
    "byg032YdervæggensMateriale": "1",
    "byg033Tagdækningsmateriale": "1",
    "byg037KildeTilBygningensMaterialer": "1",
    "byg038SamletBygningsareal": 3433,
    "byg040BygningensSamledeErhvervsAreal": 4274,
    "byg041BebyggetAreal": 447,
    "byg053BygningsarealerKilde": "1",
    "byg054AntalEtager": 7,
    "byg055AfvigendeEtager": "10",
    "byg056Varmeinstallation": "1",
    "byg069Sikringsrumpladser": 650,
    "byg094Revisionsdato": "2017-08-30T14:41:18.565858+02:00",
    "byg133KildeTilKoordinatsæt": "M",
    "byg134KvalitetAfKoordinatsæt": "1",
    "byg135SupplerendeOplysningOmKoordinatsæt": "31",
    "byg136PlaceringPåSøterritorie": "0",
    "byg404Koordinat": "POINT(721593.54 6176147.77)",
    "byg406Koordinatsystem": "5",
    "forretningshændelse": "Bygning",
    "forretningsområde": "54.15.05.05",
    "forretningsproces": "9",
    "grund": "04999352-9a5b-46ab-b669-1b2c2f890a82",
    "husnummer": "0a3f507b-4e55-32b8-e044-0003ba298018",
    "id_lokalId": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
    "id_namespace": "http://data.gov.dk/bbr/bygning",
    "jordstykke": "100028488",
    "kommunekode": "0147",
    "registreringFra": "2019-01-28T14:53:46.643651+01:00",
    "registreringsaktør": "BBR",
    "status": "6",
    "virkningFra": "2019-01-28T14:53:46.643651+01:00",
    "virkningsaktør": "Registerfører",
    "etageList": [
      {
        "id_lokalId": "d1fac880-94b6-41a5-9691-7203e53b4b1d",
        "etage": {
          "datafordelerOpdateringstid": "2021-04-03T23:47:11.793430+02:00",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "eta006BygningensEtagebetegnelse": "kl",
          "eta020SamletArealAfEtage": 841,
          "eta025Etagetype": "2",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "0",
          "id_lokalId": "d1fac880-94b6-41a5-9691-7203e53b4b1d",
          "id_namespace": "http://data.gov.dk/bbr/etage",
          "kommunekode": "0147",
          "registreringFra": "2020-06-12T18:24:45.000022+02:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2020-06-12T18:24:45.000022+02:00",
          "virkningsaktør": "BBR21"
        }
      },
      {
        "id_lokalId": "e8edcf05-e5a1-44ac-b7f0-35c99a130835",
        "etage": {
          "datafordelerOpdateringstid": "2021-04-03T23:34:20.961947+02:00",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "eta006BygningensEtagebetegnelse": "1",
          "eta025Etagetype": "0",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "25",
          "id_lokalId": "e8edcf05-e5a1-44ac-b7f0-35c99a130835",
          "id_namespace": "http://data.gov.dk/bbr/etage",
          "kommunekode": "0147",
          "registreringFra": "2017-08-19T15:06:52.939295+02:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2017-08-19T15:06:52.939295+02:00",
          "virkningsaktør": "EksterntSystem"
        }
      },
      {
        "id_lokalId": "e741d2c7-6119-450e-a8af-c3aee579a0ce",
        "etage": {
          "datafordelerOpdateringstid": "2021-04-03T23:34:20.962217+02:00",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "eta006BygningensEtagebetegnelse": "2",
          "eta025Etagetype": "0",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "25",
          "id_lokalId": "e741d2c7-6119-450e-a8af-c3aee579a0ce",
          "id_namespace": "http://data.gov.dk/bbr/etage",
          "kommunekode": "0147",
          "registreringFra": "2017-08-19T15:06:53.786008+02:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2017-08-19T15:06:53.786008+02:00",
          "virkningsaktør": "EksterntSystem"
        }
      },
      {
        "id_lokalId": "a5e54ca1-d185-40d9-8682-37a0103f0264",
        "etage": {
          "datafordelerOpdateringstid": "2021-04-03T23:34:20.962462+02:00",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "eta006BygningensEtagebetegnelse": "3",
          "eta025Etagetype": "0",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "25",
          "id_lokalId": "a5e54ca1-d185-40d9-8682-37a0103f0264",
          "id_namespace": "http://data.gov.dk/bbr/etage",
          "kommunekode": "0147",
          "registreringFra": "2017-08-19T15:06:54.720598+02:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2017-08-19T15:06:54.720598+02:00",
          "virkningsaktør": "EksterntSystem"
        }
      },
      {
        "id_lokalId": "1a9c179a-25ae-494a-872f-d407f3f0e31f",
        "etage": {
          "datafordelerOpdateringstid": "2021-04-03T23:34:20.962710+02:00",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "eta006BygningensEtagebetegnelse": "4",
          "eta025Etagetype": "0",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "25",
          "id_lokalId": "1a9c179a-25ae-494a-872f-d407f3f0e31f",
          "id_namespace": "http://data.gov.dk/bbr/etage",
          "kommunekode": "0147",
          "registreringFra": "2017-08-19T15:06:55.582929+02:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2017-08-19T15:06:55.582929+02:00",
          "virkningsaktør": "EksterntSystem"
        }
      },
      {
        "id_lokalId": "33c839c2-8703-40dc-9995-026c7a33d1ff",
        "etage": {
          "datafordelerOpdateringstid": "2021-04-03T23:34:20.962964+02:00",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "eta006BygningensEtagebetegnelse": "5",
          "eta025Etagetype": "0",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "25",
          "id_lokalId": "33c839c2-8703-40dc-9995-026c7a33d1ff",
          "id_namespace": "http://data.gov.dk/bbr/etage",
          "kommunekode": "0147",
          "registreringFra": "2017-08-19T15:06:56.426704+02:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2017-08-19T15:06:56.426704+02:00",
          "virkningsaktør": "EksterntSystem"
        }
      },
      {
        "id_lokalId": "96a78a07-cd2f-4db1-bc19-0c13667cd31a",
        "etage": {
          "datafordelerOpdateringstid": "2021-04-03T23:34:20.963229+02:00",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "eta006BygningensEtagebetegnelse": "6",
          "eta025Etagetype": "0",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "25",
          "id_lokalId": "96a78a07-cd2f-4db1-bc19-0c13667cd31a",
          "id_namespace": "http://data.gov.dk/bbr/etage",
          "kommunekode": "0147",
          "registreringFra": "2017-08-19T15:06:57.301731+02:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2017-08-19T15:06:57.301731+02:00",
          "virkningsaktør": "EksterntSystem"
        }
      },
      {
        "id_lokalId": "e6f23b64-ee28-40ea-aa6f-f6d7b3b2db61",
        "etage": {
          "datafordelerOpdateringstid": "2021-04-03T23:34:20.963478+02:00",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "eta006BygningensEtagebetegnelse": "st",
          "eta025Etagetype": "0",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "25",
          "id_lokalId": "e6f23b64-ee28-40ea-aa6f-f6d7b3b2db61",
          "id_namespace": "http://data.gov.dk/bbr/etage",
          "kommunekode": "0147",
          "registreringFra": "2017-08-19T15:06:58.205091+02:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2017-08-19T15:06:58.205091+02:00",
          "virkningsaktør": "EksterntSystem"
        }
      }
    ],
    "opgangList": [
      {
        "id_lokalId": "86cdc53f-8b83-46ff-97e5-9f85eda1aa7b",
        "opgang": {
          "datafordelerOpdateringstid": "2022-12-09T21:05:42.845371+01:00",
          "adgangFraHusnummer": "0a3f507b-4e55-32b8-e044-0003ba298018",
          "bygning": "44c1f6c7-772f-49e0-8b50-9ad065c0f369",
          "forretningshændelse": "Bygning",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "25",
          "id_lokalId": "86cdc53f-8b83-46ff-97e5-9f85eda1aa7b",
          "id_namespace": "http://data.gov.dk/bbr/opgang",
          "kommunekode": "0147",
          "opg020Elevator": "0",
          "registreringFra": "2022-12-09T17:48:01.032865+01:00",
          "registreringsaktør": "BBR",
          "status": "6",
          "virkningFra": "2018-09-14T18:49:29.546667+02:00",
          "virkningsaktør": "BBR"
        }
      }
    ]
  },
  {
    "datafordelerOpdateringstid": "2021-04-02T05:25:01.989102+02:00",
    "byg007Bygningsnummer": 1,
    "byg021BygningensAnvendelse": "420",
    "byg049ArealAfOverdækketAreal": 5,
    "byg136PlaceringPåSøterritorie": "0",
    "forretningshændelse": "Bygning",
    "forretningsområde": "54.15.05.05",
    "forretningsproces": "2",
    "grund": "04999352-9a5b-46ab-b669-1b2c2f890a82",
    "husnummer": "0a3f507b-4e55-32b8-e044-0003ba298018",
    "id_lokalId": "ce7ab0a6-1f94-4a7b-a965-5ee3c7f15828",
    "id_namespace": "http://data.gov.dk/bbr/bygning",
    "jordstykke": "100028488",
    "kommunekode": "0147",
    "registreringFra": "2017-06-02T14:29:37.000000+02:00",
    "registreringsaktør": "BBR",
    "status": "9",
    "virkningFra": "2016-09-06T10:33:04.057000+02:00",
    "virkningsaktør": "Konvertering2017"
  }
]